import { InstrumentTagData } from "../../../../Models/InstrumentTagData"
import { ColorLegendEnum } from "../../JIP33ColorLegendEnums"
import { TableRow } from "../TableRow"

export const generateInstallationConditionsRowData = (datasheet: InstrumentTagData): TableRow[] => [
        {
            refClause: "",
            description: "Upstream/high-side pipe schedule:",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.upstreamHighSidePipeSchedule,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Upstream/high-side line size:",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.upstreamHighSideLineSize,
            purchaserReqUOM: "in",
            purchaserReqUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            supplierOfferedValUOMColor: ColorLegendEnum.SelectNoInputExp,
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Upstream/high-side line equipment:",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.upstreamHighSideLineEquipmentRating,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Upstream/high-side line connection type:",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.upstreamHighSideLineConnectionType,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Upstream/high-side connection orientation:",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.upstreamHighSideConnectionOrientation,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Upstream/high-side material type:",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.upstreamHighSideMaterialType,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Design pressure, maximum:",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.designPressureMaximum,
            purchaserReqUOM: "barg",
            purchaserReqUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            supplierOfferedValUOMColor: ColorLegendEnum.SelectNoInputExp,
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Design pressure, minimum:",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.designPressureMinimum,
            purchaserReqUOM: "barg",
            purchaserReqUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            supplierOfferedValUOMColor: ColorLegendEnum.SelectNoInputExp,
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Design temperature, maximum:",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.designTemperatureMaximum,
            purchaserReqUOM: "°C",
            purchaserReqUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            supplierOfferedValUOMColor: ColorLegendEnum.SelectNoInputExp,
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Design temperature, minimum:",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.designTemperatureMinimum,
            purchaserReqUOM: "°C",
            purchaserReqUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            supplierOfferedValUOMColor: ColorLegendEnum.SelectNoInputExp,
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Sour service specification:",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.sourServiceSpecification,
            purchaserReqUOM: "",
            supplierOfferedVal: "N/A",
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
    ]
