import { InstrumentTagData } from "../../../../Models/InstrumentTagData"
import { ColorLegendEnum } from "../../JIP33ColorLegendEnums"
import { TableRow } from "../TableRow"

export const generateTransmitterRowData = (datasheet: InstrumentTagData): TableRow[] => {
    return [
        {
            refClause: "",
            description: "Transmitter model number:",
            purchaserReq: "",
            purchaserReqColor: ColorLegendEnum.InputDataNoInputExp,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.instrumentSupplierOfferedProduct?.transmitterModelNumber,
            supplierOfferedValColor: ColorLegendEnum.InputDataSupCom,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Transmitter enclosure material:",
            purchaserReq: "",
            purchaserReqColor: ColorLegendEnum.InputDataNoInputExp,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.instrumentSupplierOfferedProduct?.transmitterEnclosureMaterial,
            supplierOfferedValColor: ColorLegendEnum.InputDataSupCom,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Transmitter mounting:",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.transmitterMounting,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.instrumentSupplierOfferedProduct?.transmitterMounting,
            supplierOfferedValColor: ColorLegendEnum.SpineModification,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Transmitter display:",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.transmitterDisplay,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.instrumentSupplierOfferedProduct?.transmitterDisplay,
            supplierOfferedValColor: ColorLegendEnum.SpineModification,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Transmitter connecting cables:",
            purchaserReq: "no",
            purchaserReqColor: ColorLegendEnum.InputDataNoInputExp,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.instrumentSupplierOfferedProduct?.transmitterConnectingCables,
            supplierOfferedValColor: ColorLegendEnum.InputDataSupCom,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Transmitter connecting cable length:",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.transmitterConnectingCableLength,
            purchaserReqUOM: "",
            purchaserReqUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
            supplierOfferedVal: datasheet.instrumentSupplierOfferedProduct?.transmitterConnectingCableLength,
            supplierOfferedValColor: ColorLegendEnum.SpineModification,
            supplierOfferedValUOM: "",
            supplierOfferedValUOMColor: ColorLegendEnum.SpineModification,
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Transmitter connecting cable quantity:",
            purchaserReq: "",
            purchaserReqColor: ColorLegendEnum.SelectNoInputExp,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.instrumentSupplierOfferedProduct?.transmitterConnectingCableQuantity,
            supplierOfferedValColor: ColorLegendEnum.SelectSupComDropDown,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Supply voltage:",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.supplyVoltage,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.instrumentSupplierOfferedProduct?.supplyVoltage,
            supplierOfferedValColor: ColorLegendEnum.SpineModification,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "External power voltage:",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.externalPowerVoltage,
            purchaserReqUOM: "",
            purchaserReqUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
            supplierOfferedVal: datasheet.instrumentSupplierOfferedProduct?.externalPowerVoltage,
            supplierOfferedValColor: ColorLegendEnum.SpineModification,
            supplierOfferedValUOM: "",
            supplierOfferedValUOMColor: ColorLegendEnum.SpineModification,
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Isolated outputs:",
            purchaserReq: "N/A",
            purchaserReqColor: ColorLegendEnum.InputDataNoInputExp,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.instrumentSupplierOfferedProduct?.isolatedOutputs,
            supplierOfferedValColor: ColorLegendEnum.InputDataSupCom,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Cable entry:",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.cableEntry,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Cable termination:",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.cableTermination,
            purchaserReqColor: ColorLegendEnum.SelectEitherPurOrSupComDropDown,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.instrumentSupplierOfferedProduct?.cableTermination,
            supplierOfferedValColor: ColorLegendEnum.SelectEitherPurOrSupComDropDown,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Communication protocol:",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.communicationProtocol,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.instrumentSupplierOfferedProduct?.communicationProtocol,
            supplierOfferedValColor: ColorLegendEnum.SpineModification,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Protocol version:",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.protocolVersion,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.instrumentSupplierOfferedProduct?.protocolVersion,
            supplierOfferedValColor: ColorLegendEnum.SpineModification,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Fail safe direction:",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.failSafeDirection,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.instrumentSupplierOfferedProduct?.failSafeDirection,
            supplierOfferedValColor: ColorLegendEnum.SpineModification,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Calibration bespoke:",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.calibrationBespoke,
            purchaserReqUOM: "kg/h",
            purchaserReqUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
            supplierOfferedVal: datasheet.instrumentSupplierOfferedProduct?.calibrationBespoke,
            supplierOfferedValColor: ColorLegendEnum.SpineModification,
            supplierOfferedValUOM: "kg/h",
            supplierOfferedValUOMColor: ColorLegendEnum.SpineModification,
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Measurement range, minimum:",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.measurementRangeMinimum,
            purchaserReqUOM: "kg/h",
            purchaserReqUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
            supplierOfferedVal: datasheet.instrumentSupplierOfferedProduct?.measurementRangeMinimum,
            supplierOfferedValColor: ColorLegendEnum.SpineModification,
            supplierOfferedValUOM: "kg/h",
            supplierOfferedValUOMColor: ColorLegendEnum.SpineModification,
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Measurement range, maximum:",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.measurementRangeMaximum,
            purchaserReqUOM: "kg/h",
            purchaserReqUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
            supplierOfferedVal: datasheet.instrumentSupplierOfferedProduct?.measurementRangeMaximum,
            supplierOfferedValColor: ColorLegendEnum.SpineModification,
            supplierOfferedValUOM: "kg/h",
            supplierOfferedValUOMColor: ColorLegendEnum.SpineModification,
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Span and zero adjustment:",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.spanAndZeroAdjustment,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.instrumentSupplierOfferedProduct?.spanAndZeroAdjustment,
            supplierOfferedValColor: ColorLegendEnum.SpineModification,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Lower range limit:",
            purchaserReq: "",
            purchaserReqColor: ColorLegendEnum.InputDataNoInputExp,
            purchaserReqUOM: "",
            purchaserReqUOMColor: ColorLegendEnum.SelectNoInputExp,
            supplierOfferedVal: datasheet.instrumentSupplierOfferedProduct?.lowerRangeLimit,
            supplierOfferedValColor: ColorLegendEnum.InputDataSupCom,
            supplierOfferedValUOM: "",
            supplierOfferedValUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Upper range limit:",
            purchaserReq: "",
            purchaserReqColor: ColorLegendEnum.InputDataNoInputExp,
            purchaserReqUOM: "",
            purchaserReqUOMColor: ColorLegendEnum.SelectNoInputExp,
            supplierOfferedVal: datasheet.instrumentSupplierOfferedProduct?.upperRangeLimit,
            supplierOfferedValColor: ColorLegendEnum.InputDataSupCom,
            supplierOfferedValUOM: "",
            supplierOfferedValUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
            additionalNotes: "",
        },
    ]
}
