export const mailTerminalBoxRowData = [
    {
        refClause: "",
        description: "Position:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Ingress protection of terminal boxes:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Main terminal box cable entry hole size and number:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Oversized terminal box:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Main terminal box material:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
]
