export const motorConstructionRowData = [
    {
        refClause: "",
        description: "Motor weight:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Stainless steel hardware:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Enclosure type:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Enclosure ingress protection:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
]
