import { ElectricalTagData } from "../../../../Models/ElectricalTagData"
import { TableRow } from "../TableRow"

export const generateOperatingPerformanceRowData = (datasheet: ElectricalTagData): TableRow[] => [
        {
            refClause: "",
            description: "Rated full load speed:",
            purchaserReq: datasheet.electricalPurchaserRequirement?.ratedFullLoadSpeed,
            purchaserReqUOM: "rpm",
            supplierOfferedVal: datasheet.electricalSupplierOfferedProduct?.ratedFullLoadSpeed,
            supplierOfferedValUOM: "rpm",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Rated full load torque (FLT):",
            purchaserReq: datasheet.electricalPurchaserRequirement?.ratedFullLoadTorque,
            purchaserReqUOM: "N·m",
            supplierOfferedVal: datasheet.electricalSupplierOfferedProduct?.ratedFullLoadTorque,
            supplierOfferedValUOM: "N·m",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Rated breakdown torque:",
            purchaserReq: datasheet.electricalPurchaserRequirement?.ratedBreakdownTorque,
            purchaserReqUOM: "% of FLT",
            supplierOfferedVal: datasheet.electricalSupplierOfferedProduct?.ratedBreakdownTorque,
            supplierOfferedValUOM: "% of FLT",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Efficiency:",
            purchaserReq: datasheet.electricalPurchaserRequirement?.efficiency,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.electricalSupplierOfferedProduct?.efficiency,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Efficiency at 100% rated output:",
            purchaserReq: datasheet.electricalPurchaserRequirement?.efficiencyAt100PercentRatedOutput,
            purchaserReqUOM: "%",
            supplierOfferedVal: datasheet.electricalSupplierOfferedProduct?.efficiencyAt100PercentRatedOutput,
            supplierOfferedValUOM: "%",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Efficiency at 75% rated output:",
            purchaserReq: datasheet.electricalPurchaserRequirement?.efficiencyAt75PercentRatedOutput,
            purchaserReqUOM: "%",
            supplierOfferedVal: datasheet.electricalSupplierOfferedProduct?.efficiencyAt75PercentRatedOutput,
            supplierOfferedValUOM: "%",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Efficiency at 50% rated output:",
            purchaserReq: datasheet.electricalPurchaserRequirement?.efficiencyAt50PercentRatedOutput,
            purchaserReqUOM: "%",
            supplierOfferedVal: datasheet.electricalSupplierOfferedProduct?.efficiencyAt50PercentRatedOutput,
            supplierOfferedValUOM: "%",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Power factor at 100% rated output:",
            purchaserReq: datasheet.electricalPurchaserRequirement?.powerFactorAt100PercentRatedOutput,
            purchaserReqUOM: "pu",
            supplierOfferedVal: datasheet.electricalSupplierOfferedProduct?.powerFactorAt100PercentRatedOutput,
            supplierOfferedValUOM: "pu",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Power factor at 75% rated output:",
            purchaserReq: datasheet.electricalPurchaserRequirement?.powerFactorAt75PercentRatedOutput,
            purchaserReqUOM: "pu",
            supplierOfferedVal: datasheet.electricalSupplierOfferedProduct?.powerFactorAt75PercentRatedOutput,
            supplierOfferedValUOM: "pu",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Power factor at 50% rated output:",
            purchaserReq: datasheet.electricalPurchaserRequirement?.powerFactorAt50PercentRatedOutput,
            purchaserReqUOM: "pu",
            supplierOfferedVal: datasheet.electricalSupplierOfferedProduct?.powerFactorAt50PercentRatedOutput,
            supplierOfferedValUOM: "pu",
            additionalNotes: "",
        },
    ]
