export const operatingPerformanceRowData = [
    {
        refClause: "",
        description: "Rated full load speed:",
        purchaserReq: "",
        purchaserReqUOM: "rpm",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "rpm",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Rated full load torque (FLT):",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Rated breakdown torque:",
        purchaserReq: "",
        purchaserReqUOM: "% of FLT",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "% of FLT",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Efficiency at 100% rated output:",
        purchaserReq: "",
        purchaserReqUOM: "%",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "%",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Efficiency at 75% rated output:",
        purchaserReq: "",
        purchaserReqUOM: "%",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "%",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Efficiency at 50% rated output:",
        purchaserReq: "",
        purchaserReqUOM: "%",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "%",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Power factor at 100% rated output:",
        purchaserReq: "",
        purchaserReqUOM: "%",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "%",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Power factor at 75% rated output:",
        purchaserReq: "",
        purchaserReqUOM: "%",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "%",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Power factor at 50% rated output:",
        purchaserReq: "",
        purchaserReqUOM: "%",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "%",
        additionalNotes: "",
    },
]
