export const siteConditionsLocationEnvironmentRowData = [
    {
        refClause: "",
        description: "Floating/marine/shipboard:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Chemicals or corrosives:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Altitude:",
        purchaserReq: "",
        purchaserReqUOM: "m (ft)",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "m (ft)",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Minimum ambient air temperature:",
        purchaserReq: "",
        purchaserReqUOM: "°C (°F)",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "°C (°F)",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Maximum ambient air temperature:",
        purchaserReq: "",
        purchaserReqUOM: "°C (°F)",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "°C (°F)",
        additionalNotes: "",
    },
]
