import { ElectricalTagData } from "../../../../Models/ElectricalTagData"
import { TableRow } from "../TableRow"

export const generateSiteConditionsLocationEnvironmentRowData = (datasheet: ElectricalTagData): TableRow[] => [
        {
            refClause: "",
            description: "Location environment:",
            purchaserReq: datasheet.electricalPurchaserRequirement?.locationEnvironment,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.electricalSupplierOfferedProduct?.locationEnvironment,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Floating/marine/shipboard:",
            purchaserReq: datasheet.electricalPurchaserRequirement?.floatingMarineShipboard,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.electricalSupplierOfferedProduct?.floatingMarineShipboard,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Chemicals or corrosives:",
            purchaserReq: datasheet.electricalPurchaserRequirement?.chemicalsOrCorrosives,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.electricalSupplierOfferedProduct?.chemicalsOrCorrosives,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Altitude:",
            purchaserReq: datasheet.electricalPurchaserRequirement?.altitude,
            purchaserReqUOM: "m (ft)",
            supplierOfferedVal: datasheet.electricalSupplierOfferedProduct?.altitude,
            supplierOfferedValUOM: "m (ft)",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Minimum ambient air temperature:",
            purchaserReq: datasheet.electricalPurchaserRequirement?.minimumAmbientAirTemperature,
            purchaserReqUOM: "°C (°F)",
            supplierOfferedVal: datasheet.electricalSupplierOfferedProduct?.minimumAmbientAirTemperature,
            supplierOfferedValUOM: "°C (°F)",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Maximum ambient air temperature:",
            purchaserReq: datasheet.electricalPurchaserRequirement?.maximumAmbientAirTemperature,
            purchaserReqUOM: "°C (°F)",
            supplierOfferedVal: datasheet.electricalSupplierOfferedProduct?.maximumAmbientAirTemperature,
            supplierOfferedValUOM: "°C (°F)",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Transport and storage conditions:",
            purchaserReq: datasheet.electricalPurchaserRequirement?.transportAndStorageConditions,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.electricalSupplierOfferedProduct?.transportAndStorageConditions,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Standstill period:",
            purchaserReq: datasheet.electricalPurchaserRequirement?.standstillPeriod,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.electricalSupplierOfferedProduct?.standstillPeriod,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Maximum relative humidity:",
            purchaserReq: datasheet.electricalPurchaserRequirement?.maximumRelativeHumidity,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.electricalSupplierOfferedProduct?.maximumRelativeHumidity,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Motor enclosure ingress protection:",
            purchaserReq: datasheet.electricalPurchaserRequirement?.enclosureIngressProtection,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.electricalSupplierOfferedProduct?.enclosureIngressProtection,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Impact protection:",
            purchaserReq: datasheet.electricalPurchaserRequirement?.impactProtection,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.electricalSupplierOfferedProduct?.impactProtection,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
    ]
