export const spaceHeatersRowData = [
    {
        refClause: "",
        description: "Space heater:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "  Space heater terminal box:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "  Space heater voltage:",
        purchaserReq: "",
        purchaserReqUOM: "V AC",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "V AC",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "  Warning label:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "    Warning label language:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
]
