import { ColorLegendEnum } from "../JIP33ColorLegendEnums";

export const accessoriesRowData = [
    {
        refClause: "",
        description: "Weather enclosure:",
        purchaserReq: "select",
        purchaserReqUOM: "",
        supplierOfferedVal: "select",
        supplierOfferedValColor: ColorLegendEnum.SpineModification,
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Mounting bracket:",
        purchaserReq: "select",
        purchaserReqUOM: "",
        supplierOfferedVal: "select",
        supplierOfferedValColor: ColorLegendEnum.SpineModification,
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Mounting bracket material:",
        purchaserReq: "select",
        purchaserReqUOM: "",
        supplierOfferedVal: "select",
        supplierOfferedValColor: ColorLegendEnum.SpineModification,
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Electrical surge protector:",
        purchaserReq: "no",
        purchaserReqUOM: "",
        supplierOfferedVal: "no",
        supplierOfferedValColor: ColorLegendEnum.SpineModification,
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Sunshade:",
        purchaserReq: "no",
        purchaserReqUOM: "",
        supplierOfferedVal: "no",
        supplierOfferedValColor: ColorLegendEnum.SpineModification,
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
]
