export const accessoriesRowData = [
    {
        refClause: "",
        description: "Weather enclosure:",
        purchaserReq: "select",
        purchaserReqUOM: "",
        supplierOfferedVal: "select",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Mounting bracket:",
        purchaserReq: "select",
        purchaserReqUOM: "",
        supplierOfferedVal: "select",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Mounting bracket material:",
        purchaserReq: "select",
        purchaserReqUOM: "",
        supplierOfferedVal: "select",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Electrical surge protector:",
        purchaserReq: "no",
        purchaserReqUOM: "",
        supplierOfferedVal: "no",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Sunshade:",
        purchaserReq: "no",
        purchaserReqUOM: "",
        supplierOfferedVal: "no",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
]
