import { Datasheet } from "../../../Models/Datasheet"
import { ColorLegendEnum } from "../JIP33ColorLegendEnums"
import { TableRow } from "./TableRow"

export const generalRowData = [
    {
        refClause: "5.12,5.13,6.12",
        description: "Code requirement:",
        purchaserReq: "select",
        purchaserReqUOM: "",
        supplierOfferedVal: "select",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Conformity assessment system (CAS) level:",
        purchaserReq: "0",
        purchaserReqUOM: "",
        supplierOfferedVal: "0",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "4.12.1",
        description: "Tag number:",
        purchaserReq: "input data",
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Service description:",
        purchaserReq: "input data",
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Manufacturer:",
        purchaserReq: "input data",
        purchaserReqColor: ColorLegendEnum.InputDataEitherPurOrSupCom,
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValColor: ColorLegendEnum.InputDataEitherPurOrSupCom,
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Model number:",
        purchaserReq: "input data",
        purchaserReqColor: ColorLegendEnum.InputDataNoInputExp,
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValColor: ColorLegendEnum.InputDataSupCom,
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Equipment manufacturer serial number:",
        purchaserReq: "input data",
        purchaserReqColor: ColorLegendEnum.InputDataNoInputExp,
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValColor: ColorLegendEnum.InputDataSupCom,
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Project country:",
        purchaserReq: "input data",
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Project region:",
        purchaserReq: "input data",
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Plant environmental location:",
        purchaserReq: "select",
        purchaserReqUOM: "",
        supplierOfferedVal: "select",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "P&ID number:",
        purchaserReq: "input data",
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Line or equipment number:",
        purchaserReq: "input data",
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Minimum ambient temperature:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        purchaserReqUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
        supplierOfferedVal: "input data",
        supplierOfferedValColor: ColorLegendEnum.SpineModification,
        supplierOfferedValUOM: "select",
        supplierOfferedValUOMColor: ColorLegendEnum.SpineModification,
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Maximum ambient temperature:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        purchaserReqUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
        supplierOfferedVal: "input data",
        supplierOfferedValColor: ColorLegendEnum.SpineModification,
        supplierOfferedValUOM: "select",
        supplierOfferedValUOMColor: ColorLegendEnum.SpineModification,
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Base conditions:",
        purchaserReq: "select",
        purchaserReqUOM: "",
        supplierOfferedVal: "select",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Base temperature:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        purchaserReqUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "select",
        supplierOfferedValUOMColor: ColorLegendEnum.SelectNoInputExp,
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Base pressure:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        purchaserReqUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "select",
        supplierOfferedValUOMColor: ColorLegendEnum.SelectNoInputExp,
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Coating durability:",
        purchaserReq: "select",
        purchaserReqUOM: "",
        supplierOfferedVal: "select",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "4.3,1.2.1",
        description: "Pressure retaining bolt material:",
        purchaserReq: "select",
        purchaserReqColor: ColorLegendEnum.SelectNoInputExp,
        purchaserReqUOM: "",
        supplierOfferedVal: "select",
        supplierOfferedValColor: ColorLegendEnum.SpineModification,
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "4.3,1.2.1",
        description: "Pressure retaining nut material:",
        purchaserReq: "select",
        purchaserReqColor: ColorLegendEnum.SelectNoInputExp,
        purchaserReqUOM: "",
        supplierOfferedVal: "select",
        supplierOfferedValColor: ColorLegendEnum.SpineModification,
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "4.1.4",
        description: "SIL rating:",
        purchaserReq: "not applicable",
        purchaserReqUOM: "",
        supplierOfferedVal: "not applicable",
        supplierOfferedValColor: ColorLegendEnum.SpineModification,
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "4.1.6,6.2.1",
        description: "Ingress protection:",
        purchaserReq: "select",
        purchaserReqUOM: "",
        supplierOfferedVal: "select",
        supplierOfferedValColor: ColorLegendEnum.SpineModification,
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "4.3.3.1",
        description: "EX protection:",
        purchaserReq: "Exia",
        purchaserReqUOM: "",
        supplierOfferedVal: "Exia",
        supplierOfferedValColor: ColorLegendEnum.SpineModification,
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "4.3.3.1",
        description: "Hazardous area classification standard:",
        purchaserReq: "select",
        purchaserReqUOM: "",
        supplierOfferedVal: "select",
        supplierOfferedValColor: ColorLegendEnum.SpineModification,
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "4.3.3.1",
        description: "Explorsion hazard classification:",
        purchaserReq: "select",
        purchaserReqUOM: "",
        supplierOfferedVal: "select",
        supplierOfferedValColor: ColorLegendEnum.SpineModification,
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "4.3.3.1",
        description: "Explosion group:",
        purchaserReq: "select",
        purchaserReqUOM: "",
        supplierOfferedVal: "select",
        supplierOfferedValColor: ColorLegendEnum.SpineModification,
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "4.3.3.1",
        description: "Temperature class:",
        purchaserReq: "select",
        purchaserReqUOM: "",
        supplierOfferedVal: "select",
        supplierOfferedValColor: ColorLegendEnum.SpineModification,
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
]

export const generateGeneralRowData = (datasheet: Datasheet): TableRow[] => {
    return [
        {
            refClause: "5.12,5.13,6.12",
            description: "Code requirement:",
            purchaserReq: datasheet.purchaserRequirement?.codeRequirement,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Conformity assessment system (CAS) level:",
            purchaserReq: datasheet.purchaserRequirement?.conformityAssessmentSystemLevel,
            purchaserReqUOM: "",
            supplierOfferedVal: "0",
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "4.12.1",
            description: "Tag number:",
            purchaserReq: datasheet.purchaserRequirement?.tagNumber,
            purchaserReqUOM: "",
            supplierOfferedVal: "input data",
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Service description:",
            purchaserReq: datasheet.purchaserRequirement?.serviceDescription,
            purchaserReqUOM: "",
            supplierOfferedVal: "input data",
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Manufacturer:",
            purchaserReq: "",
            purchaserReqColor: ColorLegendEnum.InputDataEitherPurOrSupCom,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.supplierOfferedProduct?.manufacturer,
            supplierOfferedValColor: ColorLegendEnum.InputDataEitherPurOrSupCom,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Model number:",
            purchaserReq: "input data",
            purchaserReqColor: ColorLegendEnum.InputDataNoInputExp,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.supplierOfferedProduct?.modelNumber,
            supplierOfferedValColor: ColorLegendEnum.InputDataSupCom,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Equipment manufacturer serial number:",
            purchaserReq: "input data",
            purchaserReqColor: ColorLegendEnum.InputDataNoInputExp,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.supplierOfferedProduct?.equipmentManufacturerSerialNumber,
            supplierOfferedValColor: ColorLegendEnum.InputDataSupCom,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Project country:",
            purchaserReq: datasheet.purchaserRequirement?.projectCountry,
            purchaserReqUOM: "",
            supplierOfferedVal: "input data",
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Project region:",
            purchaserReq: datasheet.purchaserRequirement?.projectRegion,
            purchaserReqUOM: "",
            supplierOfferedVal: "input data",
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Plant environmental location:",
            purchaserReq: datasheet.purchaserRequirement?.plantEnvironmentalLocation,
            purchaserReqUOM: "",
            supplierOfferedVal: "select",
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "P&ID number:",
            purchaserReq: datasheet.purchaserRequirement?.pidNumber,
            purchaserReqUOM: "",
            supplierOfferedVal: "input data",
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Line or equipment number:",
            purchaserReq: datasheet.purchaserRequirement?.lineOrEquipmentNumber,
            purchaserReqUOM: "",
            supplierOfferedVal: "input data",
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Minimum ambient temperature:",
            purchaserReq: datasheet.purchaserRequirement?.minimumAmbientTemperature,
            purchaserReqUOM: "select",
            purchaserReqUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
            supplierOfferedVal: datasheet.supplierOfferedProduct?.minimumAmbientTemperature,
            supplierOfferedValColor: ColorLegendEnum.SpineModification,
            supplierOfferedValUOM: "select",
            supplierOfferedValUOMColor: ColorLegendEnum.SpineModification,
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Maximum ambient temperature:",
            purchaserReq: datasheet.purchaserRequirement?.maximumAmbientTemperature,
            purchaserReqUOM: "select",
            purchaserReqUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
            supplierOfferedVal: datasheet.supplierOfferedProduct?.maximumAmbientTemperature,
            supplierOfferedValColor: ColorLegendEnum.SpineModification,
            supplierOfferedValUOM: "select",
            supplierOfferedValUOMColor: ColorLegendEnum.SpineModification,
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Base conditions:",
            purchaserReq: datasheet.purchaserRequirement?.baseConditions,
            purchaserReqUOM: "",
            supplierOfferedVal: "select",
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Base temperature:",
            purchaserReq: datasheet.purchaserRequirement?.baseTemperature,
            purchaserReqUOM: "select",
            purchaserReqUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
            supplierOfferedVal: "input data",
            supplierOfferedValUOM: "select",
            supplierOfferedValUOMColor: ColorLegendEnum.SelectNoInputExp,
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Base pressure:",
            purchaserReq: datasheet.purchaserRequirement?.basePressure,
            purchaserReqUOM: "select",
            purchaserReqUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
            supplierOfferedVal: "input data",
            supplierOfferedValUOM: "select",
            supplierOfferedValUOMColor: ColorLegendEnum.SelectNoInputExp,
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Coating durability:",
            purchaserReq: datasheet.purchaserRequirement?.coatingDurability,
            purchaserReqUOM: "",
            supplierOfferedVal: "select",
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "4.3,1.2.1",
            description: "Pressure retaining bolt material:",
            purchaserReq: "select",
            purchaserReqColor: ColorLegendEnum.SelectNoInputExp,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.supplierOfferedProduct?.pressureRetainingBoltMaterial,
            supplierOfferedValColor: ColorLegendEnum.SpineModification,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "4.3,1.2.1",
            description: "Pressure retaining nut material:",
            purchaserReq: "select",
            purchaserReqColor: ColorLegendEnum.SelectNoInputExp,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.supplierOfferedProduct?.pressureRetainingNutMaterial,
            supplierOfferedValColor: ColorLegendEnum.SpineModification,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "4.1.4",
            description: "SIL rating:",
            purchaserReq: datasheet.purchaserRequirement?.silRating,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.supplierOfferedProduct?.silRating,
            supplierOfferedValColor: ColorLegendEnum.SpineModification,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "4.1.6,6.2.1",
            description: "Ingress protection:",
            purchaserReq: datasheet.purchaserRequirement?.ingressProtection,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.supplierOfferedProduct?.ingressProtection,
            supplierOfferedValColor: ColorLegendEnum.SpineModification,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "4.3.3.1",
            description: "EX protection:",
            purchaserReq: datasheet.purchaserRequirement?.exProtection,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.supplierOfferedProduct?.exProtection,
            supplierOfferedValColor: ColorLegendEnum.SpineModification,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "4.3.3.1",
            description: "Hazardous area classification standard:",
            purchaserReq: datasheet.purchaserRequirement?.hazardousAreaClassificationStandard,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.supplierOfferedProduct?.hazardousAreaClassificationStandard,
            supplierOfferedValColor: ColorLegendEnum.SpineModification,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "4.3.3.1",
            description: "Explorsion hazard classification:",
            purchaserReq: datasheet.purchaserRequirement?.explosionHazardClassification,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.supplierOfferedProduct?.explosionHazardClassification,
            supplierOfferedValColor: ColorLegendEnum.SpineModification,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "4.3.3.1",
            description: "Explosion group:",
            purchaserReq: datasheet.purchaserRequirement?.explosionGroup,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.supplierOfferedProduct?.explosionGroup,
            supplierOfferedValColor: ColorLegendEnum.SpineModification,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "4.3.3.1",
            description: "Temperature class:",
            purchaserReq: datasheet.purchaserRequirement?.temperatureClass,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.supplierOfferedProduct?.temperatureClass,
            supplierOfferedValColor: ColorLegendEnum.SpineModification,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
    ]
}
