export const installationConditionsRowData = [
    {
        refClause: "",
        description: "Upstream/high-side pipe schedule:",
        purchaserReq: "select",
        purchaserReqUOM: "",
        supplierOfferedVal: "select",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Upstream/high-side line size:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Upstream/high-side line equipment:",
        purchaserReq: "select",
        purchaserReqUOM: "",
        supplierOfferedVal: "select",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Upstream/high-side line connection type:",
        purchaserReq: "select",
        purchaserReqUOM: "",
        supplierOfferedVal: "select",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Upstream/high-side connection orientation:",
        purchaserReq: "input data",
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Upstream/high-side material type:",
        purchaserReq: "input data",
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Design pressure, maximum:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Design pressure, minimum:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Design temperature, maximum:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Design temperature, minimum:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Sour service specification:",
        purchaserReq: "not applicable",
        purchaserReqUOM: "",
        supplierOfferedVal: "not applicable",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
]
