import { Datasheet } from "../../../Models/Datasheet"
import { ColorLegendEnum } from "../JIP33ColorLegendEnums"
import { TableRow } from "./TableRow"

export const installationConditionsRowData = [
    {
        refClause: "",
        description: "Upstream/high-side pipe schedule:",
        purchaserReq: "select",
        purchaserReqUOM: "",
        supplierOfferedVal: "select",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Upstream/high-side line size:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        purchaserReqUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "select",
        supplierOfferedValUOMColor: ColorLegendEnum.SelectNoInputExp,
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Upstream/high-side line equipment:",
        purchaserReq: "select",
        purchaserReqUOM: "",
        supplierOfferedVal: "select",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Upstream/high-side line connection type:",
        purchaserReq: "select",
        purchaserReqUOM: "",
        supplierOfferedVal: "select",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Upstream/high-side connection orientation:",
        purchaserReq: "input data",
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Upstream/high-side material type:",
        purchaserReq: "input data",
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Design pressure, maximum:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        purchaserReqUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "select",
        supplierOfferedValUOMColor: ColorLegendEnum.SelectNoInputExp,
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Design pressure, minimum:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        purchaserReqUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "select",
        supplierOfferedValUOMColor: ColorLegendEnum.SelectNoInputExp,
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Design temperature, maximum:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        purchaserReqUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "select",
        supplierOfferedValUOMColor: ColorLegendEnum.SelectNoInputExp,
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Design temperature, minimum:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        purchaserReqUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "select",
        supplierOfferedValUOMColor: ColorLegendEnum.SelectNoInputExp,
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Sour service specification:",
        purchaserReq: "not applicable",
        purchaserReqUOM: "",
        supplierOfferedVal: "not applicable",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
]

export const generateInstallationConditionsRowData = (datasheet: Datasheet): TableRow[] => {
    return [
        {
            refClause: "",
            description: "Upstream/high-side pipe schedule:",
            purchaserReq: datasheet.purchaserRequirement?.upstreamHighSidePipeSchedule,
            purchaserReqUOM: "",
            supplierOfferedVal: "select",
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Upstream/high-side line size:",
            purchaserReq: datasheet.purchaserRequirement?.upstreamHighSideLineSize,
            purchaserReqUOM: "in",
            purchaserReqUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
            supplierOfferedVal: "input data",
            supplierOfferedValUOM: "select",
            supplierOfferedValUOMColor: ColorLegendEnum.SelectNoInputExp,
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Upstream/high-side line equipment:",
            purchaserReq: datasheet.purchaserRequirement?.upstreamHighSideLineEquipmentRating,
            purchaserReqUOM: "",
            supplierOfferedVal: "select",
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Upstream/high-side line connection type:",
            purchaserReq: datasheet.purchaserRequirement?.upstreamHighSideLineConnectionType,
            purchaserReqUOM: "",
            supplierOfferedVal: "select",
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Upstream/high-side connection orientation:",
            purchaserReq: datasheet.purchaserRequirement?.upstreamHighSideConnectionOrientation,
            purchaserReqUOM: "",
            supplierOfferedVal: "input data",
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Upstream/high-side material type:",
            purchaserReq: datasheet.purchaserRequirement?.upstreamHighSideMaterialType,
            purchaserReqUOM: "",
            supplierOfferedVal: "input data",
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Design pressure, maximum:",
            purchaserReq: datasheet.purchaserRequirement?.designPressureMaximum,
            purchaserReqUOM: "barg",
            purchaserReqUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
            supplierOfferedVal: "input data",
            supplierOfferedValUOM: "select",
            supplierOfferedValUOMColor: ColorLegendEnum.SelectNoInputExp,
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Design pressure, minimum:",
            purchaserReq: datasheet.purchaserRequirement?.designPressureMinimum,
            purchaserReqUOM: "barg",
            purchaserReqUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
            supplierOfferedVal: "input data",
            supplierOfferedValUOM: "select",
            supplierOfferedValUOMColor: ColorLegendEnum.SelectNoInputExp,
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Design temperature, maximum:",
            purchaserReq: datasheet.purchaserRequirement?.designTemperatureMaximum,
            purchaserReqUOM: "°C",
            purchaserReqUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
            supplierOfferedVal: "input data",
            supplierOfferedValUOM: "select",
            supplierOfferedValUOMColor: ColorLegendEnum.SelectNoInputExp,
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Design temperature, minimum:",
            purchaserReq: datasheet.purchaserRequirement?.designTemperatureMinimum,
            purchaserReqUOM: "°C",
            purchaserReqUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
            supplierOfferedVal: "input data",
            supplierOfferedValUOM: "select",
            supplierOfferedValUOMColor: ColorLegendEnum.SelectNoInputExp,
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Sour service specification:",
            purchaserReq: datasheet.purchaserRequirement?.sourServiceSpecification,
            purchaserReqUOM: "",
            supplierOfferedVal: "not applicable",
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
    ]
}
