export const operatingConditionsRowData = [
    {
        refClause: "",
        description: "Process fluid(s):",
        purchaserReq: "input data",
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Process fluid state:",
        purchaserReq: "select",
        purchaserReqUOM: "",
        supplierOfferedVal: "select",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Service description:",
        purchaserReq: "input data",
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Process fluid corrosive compounds:",
        purchaserReq: "input data",
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Process fluid erosion possibility:",
        purchaserReq: "select",
        purchaserReqUOM: "",
        supplierOfferedVal: "select",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Process fluid specific heat ration Cp/Cv:",
        purchaserReq: "input data",
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Process vacuum possibility:",
        purchaserReq: "select",
        purchaserReqUOM: "",
        supplierOfferedVal: "select",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Process fluid vapour pressure:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Minimum operating mass flow:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Minimum operating velocity:",
        purchaserReq: "input data",
        purchaserReqUOM: "m/s",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "m/s",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Minimum operating temperature:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Minimum operating pressure:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Minimum operating liquid specific gravity:",
        purchaserReq: "input data",
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Minimum operating liquid viscosity:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Minimum operating vapour molecular weight:",
        purchaserReq: "input data",
        purchaserReqUOM: "g/mol",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "g/mol",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Minimum operating vapour compressibility factor:",
        purchaserReq: "input data",
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Minimum operating vapour actual density:",
        purchaserReq: "input data",
        purchaserReqUOM: "kg/m2",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "kg/m2",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Minimum operating vapour viscosity:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Normal operating mass flow:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Normal operating velocity:",
        purchaserReq: "input data",
        purchaserReqUOM: "m/s",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "m/s",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Normal operating temperature:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Normal operating pressure:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Normal operating liquid specific gravity:",
        purchaserReq: "input data",
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Normal operating liquid viscosity:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Normal operating vapour molecular weight:",
        purchaserReq: "input data",
        purchaserReqUOM: "g/mol",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "g/mol",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Normal operating vapour compressibility factor:",
        purchaserReq: "input data",
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Normal operating vapour actual density:",
        purchaserReq: "input data",
        purchaserReqUOM: "kg/m2",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "kg/m2",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Normal operating vapour viscosity:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Maximum operating mass flow:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Maximum operating velocity:",
        purchaserReq: "input data",
        purchaserReqUOM: "m/s",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "m/s",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Maximum operating temperature:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Maximum operating pressure:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Maximum operating liquid specific gravity:",
        purchaserReq: "input data",
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Maximum operating liquid viscosity:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Maximum operating vapour molecular weight:",
        purchaserReq: "input data",
        purchaserReqUOM: "g/mol",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "g/mol",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Maximum operating vapour compressibility factor:",
        purchaserReq: "input data",
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Maximum operating vapour actual density:",
        purchaserReq: "input data",
        purchaserReqUOM: "kg/m2",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "kg/m2",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Maximum operating vapour viscosity:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Maximum recoverable pressure drop:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Maximum unrecoverable pressure loss:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
]
