export const performanceRowData = [
    {
        refClause: "7.1.5, 8.1.4, Table 11, Table 15",
        description: "Accuracy:",
        purchaserReq: "input data",
        purchaserReqUOM: "% of span",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "% of span",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Repeatability:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Step response:",
        purchaserReq: "input data",
        purchaserReqUOM: "ms",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "ms",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Long term drift:",
        purchaserReq: "input data",
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Long term stability:",
        purchaserReq: "input data",
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Vibration:",
        purchaserReq: "input data",
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
]
