import { ColorLegendEnum } from "../JIP33ColorLegendEnums";

export const performanceRowData = [
    {
        refClause: "7.1.5, 8.1.4, Table 11, Table 15",
        description: "Accuracy:",
        purchaserReq: "input data",
        purchaserReqColor: ColorLegendEnum.InputDataEitherPurOrSupCom,
        purchaserReqUOM: "% of span",
        purchaserReqUOMColor: ColorLegendEnum.SelectNoInputExp,
        supplierOfferedVal: "input data",
        supplierOfferedValColor: ColorLegendEnum.InputDataEitherPurOrSupCom,
        supplierOfferedValUOM: "% of span",
        supplierOfferedValUOMColor: ColorLegendEnum.SelectNoInputExp,
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Repeatability:",
        purchaserReq: "input data",
        purchaserReqColor: ColorLegendEnum.InputDataEitherPurOrSupCom,
        purchaserReqUOM: "select",
        purchaserReqUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
        supplierOfferedVal: "input data",
        supplierOfferedValColor: ColorLegendEnum.InputDataEitherPurOrSupCom,
        supplierOfferedValUOM: "select",
        supplierOfferedValUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Step response:",
        purchaserReq: "input data",
        purchaserReqColor: ColorLegendEnum.InputDataEitherPurOrSupCom,
        purchaserReqUOM: "ms",
        purchaserReqUOMColor: ColorLegendEnum.SelectNoInputExp,
        supplierOfferedVal: "input data",
        supplierOfferedValColor: ColorLegendEnum.InputDataEitherPurOrSupCom,
        supplierOfferedValUOM: "ms",
        supplierOfferedValUOMColor: ColorLegendEnum.SelectNoInputExp,
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Long term drift:",
        purchaserReq: "input data",
        purchaserReqColor: ColorLegendEnum.InputDataEitherPurOrSupCom,
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValColor: ColorLegendEnum.InputDataEitherPurOrSupCom,
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Long term stability:",
        purchaserReq: "input data",
        purchaserReqColor: ColorLegendEnum.InputDataEitherPurOrSupCom,
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValColor: ColorLegendEnum.InputDataEitherPurOrSupCom,
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Vibration:",
        purchaserReq: "input data",
        purchaserReqColor: ColorLegendEnum.InputDataEitherPurOrSupCom,
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValColor: ColorLegendEnum.InputDataEitherPurOrSupCom,
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
]
