import { ColorLegendEnum } from "../JIP33ColorLegendEnums";

export const transmitterRowData = [
    {
        refClause: "",
        description: "Transmitter model number:",
        purchaserReq: "input data",
        purchaserReqColor: ColorLegendEnum.InputDataNoInputExp,
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValColor: ColorLegendEnum.InputDataSupCom,
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Transmitter enclosure material:",
        purchaserReq: "input data",
        purchaserReqColor: ColorLegendEnum.InputDataNoInputExp,
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValColor: ColorLegendEnum.InputDataSupCom,
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Transmitter mounting:",
        purchaserReq: "integrated",
        purchaserReqUOM: "",
        supplierOfferedVal: "integrated",
        supplierOfferedValColor: ColorLegendEnum.SpineModification,
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Transmitter display:",
        purchaserReq: "integral LCD display",
        purchaserReqUOM: "",
        supplierOfferedVal: "integral LCD display",
        supplierOfferedValColor: ColorLegendEnum.SpineModification,
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Transmitter connecting cables:",
        purchaserReq: "no",
        purchaserReqColor: ColorLegendEnum.InputDataNoInputExp,
        purchaserReqUOM: "",
        supplierOfferedVal: "no",
        supplierOfferedValColor: ColorLegendEnum.InputDataSupCom,
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Transmitter connecting cable length:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        purchaserReqUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
        supplierOfferedVal: "input data",
        supplierOfferedValColor: ColorLegendEnum.SpineModification,
        supplierOfferedValUOM: "select",
        supplierOfferedValUOMColor: ColorLegendEnum.SpineModification,
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Transmitter connecting cable quantity:",
        purchaserReq: "select",
        purchaserReqColor: ColorLegendEnum.SelectNoInputExp,
        purchaserReqUOM: "",
        supplierOfferedVal: "select",
        supplierOfferedValColor: ColorLegendEnum.SelectSupComDropDown,
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Supply voltage:",
        purchaserReq: "24 V DC loop power",
        purchaserReqUOM: "",
        supplierOfferedVal: "24 V DC loop power",
        supplierOfferedValColor: ColorLegendEnum.SpineModification,
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "External power voltage:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        purchaserReqUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
        supplierOfferedVal: "input data",
        supplierOfferedValColor: ColorLegendEnum.SpineModification,
        supplierOfferedValUOM: "select",
        supplierOfferedValUOMColor: ColorLegendEnum.SpineModification,
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Isolated outputs:",
        purchaserReq: "not applicable",
        purchaserReqColor: ColorLegendEnum.InputDataNoInputExp,
        purchaserReqUOM: "",
        supplierOfferedVal: "not applicable",
        supplierOfferedValColor: ColorLegendEnum.InputDataSupCom,
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Cable entry:",
        purchaserReq: "M20 x 1.5",
        purchaserReqUOM: "",
        supplierOfferedVal: "M20 x 1.5",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Cable termination:",
        purchaserReq: "select",
        purchaserReqColor: ColorLegendEnum.SelectEitherPurOrSupComDropDown,
        purchaserReqUOM: "",
        supplierOfferedVal: "select",
        supplierOfferedValColor: ColorLegendEnum.SelectEitherPurOrSupComDropDown,
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Communication protocol:",
        purchaserReq: "4-20mA HART",
        purchaserReqUOM: "",
        supplierOfferedVal: "4-20mA HART",
        supplierOfferedValColor: ColorLegendEnum.SpineModification,
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Protocol version:",
        purchaserReq: "input data",
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValColor: ColorLegendEnum.SpineModification,
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Fail safe direction:",
        purchaserReq: "fail low (NAMUR)",
        purchaserReqUOM: "",
        supplierOfferedVal: "fail low (NAMUR)",
        supplierOfferedValColor: ColorLegendEnum.SpineModification,
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Calibration bespoke:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        purchaserReqUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
        supplierOfferedVal: "input data",
        supplierOfferedValColor: ColorLegendEnum.SpineModification,
        supplierOfferedValUOM: "select",
        supplierOfferedValUOMColor: ColorLegendEnum.SpineModification,
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Measurement range, minimum:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        purchaserReqUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
        supplierOfferedVal: "input data",
        supplierOfferedValColor: ColorLegendEnum.SpineModification,
        supplierOfferedValUOM: "select",
        supplierOfferedValUOMColor: ColorLegendEnum.SpineModification,
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Measurement range, maximum:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        purchaserReqUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
        supplierOfferedVal: "input data",
        supplierOfferedValColor: ColorLegendEnum.SpineModification,
        supplierOfferedValUOM: "select",
        supplierOfferedValUOMColor: ColorLegendEnum.SpineModification,
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Span and zero adjustment:",
        purchaserReq: "select",
        purchaserReqUOM: "",
        supplierOfferedVal: "select",
        supplierOfferedValColor: ColorLegendEnum.SpineModification,
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Lower range limit:",
        purchaserReq: "input data",
        purchaserReqColor: ColorLegendEnum.InputDataNoInputExp,
        purchaserReqUOM: "select",
        purchaserReqUOMColor: ColorLegendEnum.SelectNoInputExp,
        supplierOfferedVal: "input data",
        supplierOfferedValColor: ColorLegendEnum.InputDataSupCom,
        supplierOfferedValUOM: "select",
        supplierOfferedValUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Upper range limit:",
        purchaserReq: "input data",
        purchaserReqColor: ColorLegendEnum.InputDataNoInputExp,
        purchaserReqUOM: "select",
        purchaserReqUOMColor: ColorLegendEnum.SelectNoInputExp,
        supplierOfferedVal: "input data",
        supplierOfferedValColor: ColorLegendEnum.InputDataSupCom,
        supplierOfferedValUOM: "select",
        supplierOfferedValUOMColor: ColorLegendEnum.SelectUnitsOfDropDown,
        additionalNotes: "",
    },
]
