import { InstrumentTagData } from "../../../Models/InstrumentTagData"
import { TableRow } from "../../JIP33Table/RowData/TableRow"

export const equipmentConditionsRowData = (datasheet: InstrumentTagData): TableRow[] => [
        {
            refClause: "",
            description: "Line nominal size",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.lineNominalSize,
            purchaserReqUOM: "inch",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Line inner diameter",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.lineInnerDiameter,
            purchaserReqUOM: "mm",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Line material",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.lineMaterial,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Flange standard or code",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.flangeStandardOrCode,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Flange size",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.flangeSize,
            purchaserReqUOM: "inch",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Flange pressure class",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.flangePressureClass,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Flange facing",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.flangeFacing,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Piping design temperature",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.pipingDesignTemperature,
            purchaserReqUOM: "°C",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Piping design pressure",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.pipingDesignPressure,
            purchaserReqUOM: "barg",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Fluid",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.fluid,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Phase",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.phase,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Corrosive Compounds",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.corrosiveCompounds,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Maximum pressure loss",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.maximumPressureLoss,
            purchaserReqUOM: "bar",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "Note 2",
            property: "",
        },
    ]
