import { InstrumentTagData } from "../../../Models/InstrumentTagData"
import { TableRow } from "../../JIP33Table/RowData/TableRow"

export const generalRowData = (datasheet: InstrumentTagData): TableRow[] => {
    return [
        {
            refClause: "",
            description: "Tag number",
            purchaserReq: datasheet.tagNo,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Service description",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.serviceDescription,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "P&ID",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.pAndID,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Line/equipment no",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.lineEquipmentNumber,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Pipe class sheet",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.pipeClassSheet,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Set/alarm point",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.setAlarmPoint,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Area",
            purchaserReq: datasheet.area,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "P.O. number",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.poNumber,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Type",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.type,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Manufacturer",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.manufacturer,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Operating Temp Limits",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.operatingTemperatureLimits,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Operating Press. Limit",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.operatingPressureLimit,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Press. loss at full range",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.pressureLossAtFullRange,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Mounting",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.mounting,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Weight",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.weight,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Other",
            purchaserReq: "NA",
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
    ]
}