import { InstrumentTagData } from "../../../Models/InstrumentTagData"
import { TableRow } from "../../JIP33Table/RowData/TableRow"

export const meterBodyRowData = (datasheet: InstrumentTagData): TableRow[] => {
    return [
        {
            refClause: "",
            description: "Nominal size",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.bodyNominalSize,
            purchaserReqUOM: "inch",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Manufacturer model no",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.bodyElementSensorManufacturerModelNumber,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Process conn. size/type",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.processConnectionSizeType,
            purchaserReqUOM: "lb",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Pressure rating",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.pressureRating,
            purchaserReqUOM: "lb",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Face to face dimension",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.faceToFaceDimension,
            purchaserReqUOM: "mm",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Number of tube runs",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.numberOfTubeRuns,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Tube inner diameter",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.tubeInnerDiameter,
            purchaserReqUOM: "mm",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Material, tube",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.materialTube,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Material, flange/connect.",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.materialFlangeConnection,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Sour service spec.",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.sourServiceSpecification,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Material, tube cover",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.materialTubeCover,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Enclosure protection",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.bodyEnclosureProtection,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Protective coating/color",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.bodyProtectiveCoatingColor,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Other",
            purchaserReq: "NA",
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
    ]
}
