import { InstrumentTagData } from "../../../Models/InstrumentTagData"
import { TableRow } from "../../JIP33Table/RowData/TableRow"

export const operatingConditionsMinimumFlowRowData = (datasheet: InstrumentTagData): TableRow[] => [
        {
            refClause: "",
            description: "Flow rate",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.minimumFlowRate,
            purchaserReqUOM: "kg/h",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Velocity",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.minimumOperatingVelocity,
            purchaserReqUOM: "m/s",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "Note 3",
            property: "",
        },
        {
            refClause: "",
            description: "Temperature",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.minimumOperatingTemperature,
            purchaserReqUOM: "°C",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "Note 1",
            property: "",
        },
        {
            refClause: "",
            description: "Inlet Pressure",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.minimumInletPressure,
            purchaserReqUOM: "bara",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Density at T and P",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.minimumDensityAtTAndP,
            purchaserReqUOM: "kg/m3",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "Note 1",
            property: "",
        },
        {
            refClause: "",
            description: "Viscosity at T",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.minimumViscosityAtT,
            purchaserReqUOM: "cP",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "Note 1",
            property: "",
        },
        {
            refClause: "",
            description: "Vapour molecular weight",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.minimumOperatingVapourMolecularWeight,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Vapour compress. factor",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.minimumVapourCompressFactor,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
        {
            refClause: "",
            description: "Vapour specific heat ratio",
            purchaserReq: datasheet.instrumentPurchaserRequirement?.minimumVapourSpecificHeatRatio,
            purchaserReqUOM: "",
            supplierOfferedVal: "",
            supplierOfferedValUOM: "",
            additionalNotes: "",
            property: "",
        },
    ]
