import { MechanicalTagData } from "../../../../Models/MechanicalTagData";
import { TagData } from "../../../../Models/TagData";
import { TableRow } from "../TableRow";

export const generateBearingsAndLubricationRowData = (datasheet: MechanicalTagData): TableRow[] => {
    return [
        {
            refClause: "",
            description: "Radial bearing type:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.radialBearingType,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.radialBearingType,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Thrust type bearing:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.thrustTypeBearing,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.thrustTypeBearing,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Review and acceptance of thrust bearing size:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.reviewAndAcceptanceOfThrustBearingSize,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.reviewAndAcceptanceOfThrustBearingSize,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Rolling element bearing life calculations:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.rollingElementBearingLifeCalculations,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.rollingElementBearingLifeCalculations,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Lubrication:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.lubrication,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.lubrication,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Oil viscosity ISO grade:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.oilViscosityISOGrade,
            purchaserReqUOM: "ISO VG",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.oilViscosityISOGrade,
            supplierOfferedValUOM: "ISO VG",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Oil type:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.oilType,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.oilType,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Grease type:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.greaseType,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.greaseType,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Grease grade:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.greaseGrade,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.greaseGrade,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Bearing housing sealing type/model:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.bearingHousingSealingTypeModel,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.bearingHousingSealingTypeModel,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Oil mist reclassifiers supplied by:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.oilMistReclassifiersSuppliedBy,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.oilMistReclassifiersSuppliedBy,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
    ]
}
