export const driverAndGearRowData = [
    {
        refClause: "",
        description: "Driver type:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Driver specification:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Driver manufacturer:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Driver rating:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Driver sized for testing on water:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Driver frame or model:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Driver nameplate power:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Driver nominal speed:",
        purchaserReq: "",
        purchaserReqUOM: "rpm",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "rpm",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Driver rated load speed:",
        purchaserReq: "",
        purchaserReqUOM: "rpm",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "rpm",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Driver lubrication method:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Driver radial bearing type:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Driver thrust bearing type:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Motor starting method:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Adjustable speed drive:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Source of adjustable speed drive:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Required trip speed:",
        purchaserReq: "",
        purchaserReqUOM: "rpm",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "rpm",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Gear:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Gear specification:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Gear/adjustable speed drive manufacturer:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
]
