import { MechanicalTagData } from "../../../../Models/MechanicalTagData";
import { TagData } from "../../../../Models/TagData";
import { TableRow } from "../TableRow";

export const generateGeneralRowData = (datasheet: MechanicalTagData): TableRow[] => {
    return [
        {
            refClause: "",
            description: "Conformity assessment system (CAS) level:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.conformityAssesmentSystemLevel,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.conformityAssesmentSystemLevel,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Tag number:",
            purchaserReq: datasheet.tagNo,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.tagNo,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Tag description:",
            purchaserReq: datasheet.description,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.description,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Applicable to:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.applicableTo,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.applicableTo,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Units:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.units,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.units,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Manufacturer:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.manufacturer,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.manufacturer,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Pump model and size:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.pumpModelAndSize,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.pumpModelAndSize,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Number of stages:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.numberOfStages,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.numberOfStages,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Number of pump units:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.numberOfPumpUnits,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.numberOfPumpUnits,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Service type:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.serviceType,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.serviceType,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Number of starts:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.numberOfStarts,
            purchaserReqUOM: "per week",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.numberOfStarts,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Instantaneous start-up:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.instantaneousStartUp,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.instantaneousStartUp,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Pump operational mode:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.pumpOperationalMode,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.pumpOperationalMode,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Pump start-up mode:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.pumpStartUpMode,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.pumpStartUpMode,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Individual pump flow control:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.individualPumpFlowControl,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.individualPumpFlowControl,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
    ]
}
