export const generalRowData = [
    {
        refClause: "",
        description: "Conformity assessment system (CAS) level:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Tag number:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Tag description:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Applicable to:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Units:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Manufacturer:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Pump model and size:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Number of stages:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Number of pump units:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Service type:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Number of starts:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Instantaneous start-up:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Pump operational mode:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Pump start-up mode:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Individual pump flow control:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
]
