export const liquidCharacteristicsRowData = [
    {
        refClause: "",
        description: "Liquid name:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Liquid type:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Vapor pressure at rated temperature:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Vapor pressure maximum:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Vapor pressure minimum:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Relative density rated:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Relative density maximum:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Relative density minimum:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Specific heat rated:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Specific heat maximum:",
        purchaserReq: "",
        purchaserReqUOM: "selec",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Specific heat minimum:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Viscosity rated:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Viscosity maximum:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Viscosity minimum:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Corrosive constituents:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Erosive constituents:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "H2S concentration:",
        purchaserReq: "",
        purchaserReqUOM: "ppm",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "ppm",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Chloride concentration:",
        purchaserReq: "",
        purchaserReqUOM: "ppm",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "ppm",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Total dissolved salts:",
        purchaserReq: "",
        purchaserReqUOM: "ppm",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "ppm",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Particulate size:",
        purchaserReq: "",
        purchaserReqUOM: "μm",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "μm",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Particulate concentration:",
        purchaserReq: "",
        purchaserReqUOM: "ppm",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "ppm",
        additionalNotes: "",
    },
]
