import { MechanicalTagData } from "../../../../Models/MechanicalTagData";
import { TagData } from "../../../../Models/TagData";
import { TableRow } from "../TableRow";

export const generateLiquidCharacteristicsRowData = (datasheet: MechanicalTagData): TableRow[] => {
    return [
        {
            refClause: "",
            description: "Liquid name:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.liquidName,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.liquidName,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Liquid type:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.liquidType,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.liquidType,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Vapor pressure at rated temperature:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.vaporPressureAtRatedTemperature,
            purchaserReqUOM: "bar a",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.vaporPressureAtRatedTemperature,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Vapor pressure maximum:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.vaporPressureMaximum,
            purchaserReqUOM: "bar a",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.vaporPressureMaximum,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Vapor pressure minimum:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.vaporPressureMinimum,
            purchaserReqUOM: "bar a",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.vaporPressureMinimum,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Relative density rated:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.relativeDensityRated,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.relativeDensityRated,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Relative density maximum:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.relativeDensityMaximum,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.relativeDensityMaximum,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Relative density minimum:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.relativeDensityMinimum,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.relativeDensityMinimum,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Specific heat rated:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.specificHeatRated,
            purchaserReqUOM: "select",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.specificHeatRated,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Specific heat maximum:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.specificHeatMaximum,
            purchaserReqUOM: "select",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.specificHeatMaximum,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Specific heat minimum:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.specificHeatMinimum,
            purchaserReqUOM: "select",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.specificHeatMinimum,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Viscosity rated:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.viscosityRated,
            purchaserReqUOM: "cP",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.viscosityRated,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Viscosity maximum:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.viscosityMaximum,
            purchaserReqUOM: "cP",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.viscosityMaximum,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Viscosity minimum:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.viscosityMinimum,
            purchaserReqUOM: "cP",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.viscosityMinimum,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Corrosive constituents:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.corrosiveConstituents,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.corrosiveConstituents,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Erosive constituents:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.erosiveConstituents,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.erosiveConstituents,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "H2S concentration:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.h2SConcentration,
            purchaserReqUOM: "ppm",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.h2SConcentration,
            supplierOfferedValUOM: "ppm",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Chloride concentration:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.chlorideConcentration,
            purchaserReqUOM: "ppm",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.chlorideConcentration,
            supplierOfferedValUOM: "ppm",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Total dissolved salts:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.totalDissolvedSalts,
            purchaserReqUOM: "ppm",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.totalDissolvedSalts,
            supplierOfferedValUOM: "ppm",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Particulate size:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.particulateSize,
            purchaserReqUOM: "μm",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.particulateSize,
            supplierOfferedValUOM: "μm",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Particulate concentration:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.particulateConcentration,
            purchaserReqUOM: "ppm",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.particulateConcentration,
            supplierOfferedValUOM: "ppm",
            additionalNotes: "",
        },
    ]
}
