import { Datasheet } from "../../../../Models/Datasheet";
import { TableRow } from "../TableRow";

export const generateMaterialsAddForVerticalPumpsRowData = (datasheet: Datasheet): TableRow[] => {
    return [
        {
            refClause: "",
            description: "Suction barrel/can material:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.suctionBarrelCanMaterial,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.suctionBarrelCanMaterial,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Discharge head material:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.dischargeHeadMaterial,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.dischargeHeadMaterial,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Discharge column material:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.dischargeColumnMaterial,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.dischargeColumnMaterial,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Head column material:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.headColumnMaterial,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.headColumnMaterial,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Discharge elbow and pipe material:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.dischargeElbowAndPipeMaterial,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.dischargeElbowAndPipeMaterial,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Bowl/casing material:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.bowlCasingMaterial,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.bowlCasingMaterial,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Bellmouth/suction cover material:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.bellmouthSuctionCoverMaterial,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.bellmouthSuctionCoverMaterial,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Strainer material:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.strainerMaterial,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.strainerMaterial,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Line shaft material:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.lineShaftMaterial,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.lineShaftMaterial,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Shaft enclosing tube material:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.shaftEnclosingTubeMaterial,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.shaftEnclosingTubeMaterial,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Bowl shaft material:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.bowlShaftMaterial,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.bowlShaftMaterial,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Process wetted fasteners material:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.processWettedFastenersMaterial,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.processWettedFastenersMaterial,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Bearing retainer or spider material:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.bearingRetainerOrSpiderMaterial,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.bearingRetainerOrSpiderMaterial,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Line shaft bearing material:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.lineShaftBearingMaterial,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.lineShaftBearingMaterial,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Line shaft hard facing material:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.lineShaftHardFacingMaterial,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.lineShaftHardFacingMaterial,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Line shaft sleeves material:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.lineShaftSleevesMaterial,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.lineShaftSleevesMaterial,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Bearing lubrication lines material:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.bearingLubricationLinesMaterial,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.bearingLubricationLinesMaterial,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Bowl bearing material:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.bowlBearingMaterial,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.bowlBearingMaterial,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
    ]
}
