export const materialsAddForVerticalPumpsRowData = [
    {
        refClause: "",
        description: "Suction barrel/can material:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Discharge head material:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Discharge column material:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Head column material:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Discharge elbow and pipe material:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Bowl/casing material:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Bellmouth/suction cover material:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Strainer material:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Line shaft material:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Shaft enclosing tube material:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Bowl shaft material:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Process wetted fasteners material:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Bearing retainer or spider material:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Line shaft bearing material:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Line shaft hard facing material:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Line shaft sleeves material:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Bearing lubrication lines material:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Bowl bearing material:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
]
