export const operatingConditionsRowData = [
    {
        refClause: "",
        description: "NPSHA datum:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Flow rated:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Flow normal:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Flow maximum:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Flow minumum:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Flow alternative condition:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "NPSHA rated:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "NPSHA normal:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "NPSHA maximum:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "NPSHA minimum:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "NPSHA alternative condition:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "NPSHA at 120% of rated flow:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Pumping temperature rated:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Pumping temperature normal:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Pumping temperature maximum:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Pumping temperature minimum:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Pumping temperature alternative condition:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Discharge pressure rated:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Discharge pressure maximum:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Discharge pressure alternative condition:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Suction pressure rated:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Suction pressure normal:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Suction pressure maximum:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Suction pressure minimum:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Suction pressure alternative condition:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Differential pressure rated:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Differential pressure alternative condition:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Differential head rated:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Differential head alternative condition:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Hydraulic power:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
]
