import { Datasheet } from "../../../../Models/Datasheet";
import { TableRow } from "../TableRow";

export const generateOperatingConditionsRowData = (datasheet: Datasheet): TableRow[] => {
    return [
        {
            refClause: "",
            description: "NPSHA datum:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.npshaDatum,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.npshaDatum,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Flow rated:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.flowRated,
            purchaserReqUOM: "m3/h",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.flowRated,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Flow normal:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.flowNormal,
            purchaserReqUOM: "m3/h",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.flowNormal,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Flow maximum:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.flowMaximum,
            purchaserReqUOM: "m3/h",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.flowMaximum,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Flow minumum:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.flowMinimum,
            purchaserReqUOM: "m3/h",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.flowMinimum,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Flow alternative condition:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.flowAlternativeCondition,
            purchaserReqUOM: "m3/h",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.flowAlternativeCondition,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "NPSHA rated:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.npshaRated,
            purchaserReqUOM: "m",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.npshaRated,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "NPSHA normal:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.npshaNormal,
            purchaserReqUOM: "m",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.npshaNormal,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "NPSHA maximum:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.npshaMaximum,
            purchaserReqUOM: "m",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.npshaMaximum,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "NPSHA minimum:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.npshaMinimum,
            purchaserReqUOM: "m",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.npshaMinimum,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "NPSHA alternative condition:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.npshaAlternativeCondition,
            purchaserReqUOM: "m",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.npshaAlternativeCondition,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "NPSHA at 120% of rated flow:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.npshaAt120PercentOfRatedFlow,
            purchaserReqUOM: "m",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.npshaAt120PercentOfRatedFlow,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Pumping temperature rated:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.pumpingTemperatureRated,
            purchaserReqUOM: "°C",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.pumpingTemperatureRated,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Pumping temperature normal:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.pumpingTemperatureNormal,
            purchaserReqUOM: "°C",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.pumpingTemperatureNormal,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Pumping temperature maximum:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.pumpingTemperatureMaximum,
            purchaserReqUOM: "°C",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.pumpingTemperatureMaximum,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Pumping temperature minimum:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.pumpingTemperatureMinimum,
            purchaserReqUOM: "°C",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.pumpingTemperatureMinimum,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Pumping temperature alternative condition:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.pumpingTemperatureAlternativeCondition,
            purchaserReqUOM: "°C",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.pumpingTemperatureAlternativeCondition,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Discharge pressure rated:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.dischargePressureRated,
            purchaserReqUOM: "bar g",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.dischargePressureRated,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Discharge pressure maximum:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.dischargePressureMaximum,
            purchaserReqUOM: "bar g",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.dischargePressureMaximum,
            supplierOfferedValUOM: "bar g",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Discharge pressure alternative condition:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.dischargePressureAlternativeCondition,
            purchaserReqUOM: "bar g",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.dischargePressureAlternativeCondition,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Suction pressure rated:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.suctionPressureRated,
            purchaserReqUOM: "bar a",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.suctionPressureRated,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Suction pressure normal:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.suctionPressureNormal,
            purchaserReqUOM: "bar a",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.suctionPressureNormal,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Suction pressure maximum:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.suctionPressureMaximum,
            purchaserReqUOM: "select",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.suctionPressureMaximum,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Suction pressure minimum:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.suctionPressureMinimum,
            purchaserReqUOM: "bar a",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.suctionPressureMinimum,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Suction pressure alternative condition:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.suctionPressureAlternativeCondition,
            purchaserReqUOM: "bar g",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.suctionPressureAlternativeCondition,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Differential pressure rated:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.differentialPressureRated,
            purchaserReqUOM: "bar",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.differentialPressureRated,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Differential pressure alternative condition:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.differentialPressureAlternativeCondition,
            purchaserReqUOM: "bar",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.differentialPressureAlternativeCondition,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Differential head rated:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.differentialHeadRated,
            purchaserReqUOM: "m",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.differentialHeadRated,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Differential head alternative condition:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.differentialHeadAlternativeCondition,
            purchaserReqUOM: "m",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.differentialHeadAlternativeCondition,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Hydraulic power:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.hydraulicPower,
            purchaserReqUOM: "kW",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.hydraulicPower,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
    ]
}
