import { MechanicalTagData } from "../../../../Models/MechanicalTagData";
import { TagData } from "../../../../Models/TagData";
import { TableRow } from "../TableRow";

export const generatePerformanceRowData = (datasheet: MechanicalTagData): TableRow[] => {
    return [
        {
            refClause: "",
            description: "Proposal curve number:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.proposalCurveNumber,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.proposalCurveNumber,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Impeller diameter rated:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.impellerDiameterRated,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.impellerDiameterRated,
            supplierOfferedValUOM: "mm",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Impeller diameter maximum:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.impellerDiameterMaximum,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.impellerDiameterMaximum,
            supplierOfferedValUOM: "mm",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Impeller diameter minimum:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.impellerDiameterMinimum,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.impellerDiameterMinimum,
            supplierOfferedValUOM: "mm",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Rated speed:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.ratedSpeed,
            purchaserReqUOM: "rpm",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.ratedSpeed,
            supplierOfferedValUOM: "rpm",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Rated power:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.ratedPower,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.ratedPower,
            supplierOfferedValUOM: "kW",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Efficiency:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.efficiency,
            purchaserReqUOM: "%",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.efficiency,
            supplierOfferedValUOM: "%",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Proposal curve BEP flow (at rated impeller diameter):",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.proposalCurveBEPFlow,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.proposalCurveBEPFlow,
            supplierOfferedValUOM: "m3/h",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Minimum flow thermal:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.minimumFlowThermal,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.minimumFlowThermal,
            supplierOfferedValUOM: "m3/h",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Minimum flow stable:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.minimumFlowStable,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.minimumFlowStable,
            supplierOfferedValUOM: "m3/h",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Start of preferred operating region:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.startOfPreferredOperatingRegion,
            purchaserReqUOM: "select",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.startOfPreferredOperatingRegion,
            supplierOfferedValUOM: "select",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "End of preferred operating region:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.endOfPreferredOperatingRegion,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.endOfPreferredOperatingRegion,
            supplierOfferedValUOM: "m3/h",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Start of allowable operating region:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.startOfAllowableOperatingRegion,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.startOfAllowableOperatingRegion,
            supplierOfferedValUOM: "m3/h",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "End of allowable operating region:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.endOfAllowableOperatingRegion,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.endOfAllowableOperatingRegion,
            supplierOfferedValUOM: "m3/h",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Maximum head at rated impeller:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.maximumHeadAtRatedImpeller,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.maximumHeadAtRatedImpeller,
            supplierOfferedValUOM: "m",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Maximum power at rated impeller:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.maximumPowerAtRatedImpeller,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.maximumPowerAtRatedImpeller,
            supplierOfferedValUOM: "kW",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "NPSH3 at rated flow:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.npsH3AtRatedFlow,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.npsH3AtRatedFlow,
            supplierOfferedValUOM: "m",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "NPSH3 at 120 % of flow:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.npsH3At120PercentOfFlow,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.npsH3At120PercentOfFlow,
            supplierOfferedValUOM: "m",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "NPSHA-NPSH3 margin at rated flow:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.npshanpsH3MarginAtRatedFlow,
            purchaserReqUOM: "m",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.npshanpsH3MarginAtRatedFlow,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "NPSHA-NPSH3 margin in allowable operating region:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.npshanpsH3MarginInAllowableOperatingRegion,
            purchaserReqUOM: "m",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.npshanpsH3MarginInAllowableOperatingRegion,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Specific speed:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.specificSpeed,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.specificSpeed,
            supplierOfferedValUOM: "m3/s rpm m",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Suction-specific speed:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.suctionSpecificSpeed,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.suctionSpecificSpeed,
            supplierOfferedValUOM: "m3/s rpm m",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Maximum allowable sound pressure level:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.maximumAllowableSoundPressureLevel,
            purchaserReqUOM: "dB(A)",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.maximumAllowableSoundPressureLevel,
            supplierOfferedValUOM: "dB(A)",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Maximum allowable sound power level:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.maximumAllowableSoundPowerLevel,
            purchaserReqUOM: "dB(A)",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.maximumAllowableSoundPowerLevel,
            supplierOfferedValUOM: "dB(A)",
            additionalNotes: "",
        },
    ]
}
