import { MechanicalTagData } from "../../../../Models/MechanicalTagData";
import { TagData } from "../../../../Models/TagData";
import { TableRow } from "../TableRow";

export const generateSiteDataRowData = (datasheet: MechanicalTagData): TableRow[] => {
    return [
        {
            refClause: "",
            description: "Project country:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.projectCountry,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.projectCountry,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Project region:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.projectRegion,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.projectRegion,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Plant environmental location:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.plantEnvironmentalLocation,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.plantEnvironmentalLocation,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Equipment location:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.equipmentLocation,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.equipmentLocation,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Location climate:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.locationClimate,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.locationClimate,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Location sunlight protection:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.locationSunlightProtection,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.locationSunlightProtection,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Mounting:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.siteDataMounting,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.siteDataMounting,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Special weather protection:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.specialWeatherProtection,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.specialWeatherProtection,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Elevation:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.elevation,
            purchaserReqUOM: "m",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.elevation,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Barometer:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.barometer,
            purchaserReqUOM: "bar a",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.barometer,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Maximum ambient temperature:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.maximumAmbientTemperature,
            purchaserReqUOM: "°C",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.maximumAmbientTemperature,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Minimum ambient temperature:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.minimumAmbientTemperature,
            purchaserReqUOM: "°C",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.minimumAmbientTemperature,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Maximum relative humidity:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.maximumRelativeHumidity,
            purchaserReqUOM: "%",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.maximumRelativeHumidity,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Minimum relative humidity:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.minimumRelativeHumidity,
            purchaserReqUOM: "%",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.minimumRelativeHumidity,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Unusual conditions:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.unusualConditions,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.unusualConditions,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Floating applications motion design criteria:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.floatingApplicationsMotionDesignCriteria,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.floatingApplicationsMotionDesignCriteria,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Hazardous area certification standard:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.hazardousAreaClassificationStandard,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.hazardousAreaClassificationStandard,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Explosion hazard classification (IEC):",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.explosionHazardClassificationIEC,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.explosionHazardClassificationIEC,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Explosion gas group (IEC):",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.explosionGasGroupIEC,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.explosionGasGroupIEC,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Temperature class (IEC):",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.temperatureClassIEC,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.temperatureClassIEC,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Explosion hazard classification (NFPA):",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.explosionHazardClassificationNFPA,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.explosionHazardClassificationNFPA,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Explosion gas group (NFPA):",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.explosionGasGroupNFPA,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.explosionGasGroupNFPA,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Temperature class (NFPA):",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.temperatureClassNFPA,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.temperatureClassNFPA,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
        {
            refClause: "",
            description: "Ignition hazard assessment:",
            purchaserReq: datasheet.mechanicalPurchaserRequirement?.ignitionHazardAssessment,
            purchaserReqUOM: "",
            supplierOfferedVal: datasheet.mechanicalSupplierOfferedProduct?.ignitionHazardAssessment,
            supplierOfferedValUOM: "",
            additionalNotes: "",
        },
    ]
}
