export const sparePartsRowData = [
    {
        refClause: "",
        description: "Commissioning and start-up spares quotation:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Normal maintenance spares quotation:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Two-year operating spares quotation:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Capital spares quotation:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Spare rotor storage orientation:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Shipping and storage container for vertical storage of spare rotor:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Inert gas purge for spare rotor container:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
]
