export const utilityConditionsRowData = [
    {
        refClause: "",
        description: "Drivers voltage:",
        purchaserReq: "",
        purchaserReqUOM: "V",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "V",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Drivers phase:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Driver frequency:",
        purchaserReq: "",
        purchaserReqUOM: "Hz",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "Hz",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Heating medium:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Heating voltage:",
        purchaserReq: "",
        purchaserReqUOM: "V",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "V",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Heating phase:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Heating frequency:",
        purchaserReq: "",
        purchaserReqUOM: "Hz",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "Hz",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Heating steam minimum temperature:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Heating steam maximum temperature:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Heating steam minimum pressure:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Heating steam maximum pressure:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Cooling water maximum inlet temperature:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Cooling water design temperature:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Cooling water maximum inlet pressure:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Cooling water design pressure:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Cooling water type:",
        purchaserReq: "",
        purchaserReqUOM: "",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Fouling factor:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Cooling water chloride concentration:",
        purchaserReq: "",
        purchaserReqUOM: "ppm",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "ppm",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Instrument air minimum pressure:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Instrument air maximum pressure:",
        purchaserReq: "",
        purchaserReqUOM: "select",
        supplierOfferedVal: "",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
]
